config/routes.rb
Rails.application.routes.draw do
  resources :cadastros
  resources :cadastro_usuarios

  get 'bem_vindo' => 'paginas#inicio'

  
  get 'cadastro' => 'cadastros#index'

end

app/models/cadastro.rb
class Cadastro < ActiveRecord::Base
end

app/models/cadastro_usuario.rb
class CadastroUsuario < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cadastro_usuarios_controller.rb
class CadastroUsuariosController < ApplicationController
  before_action :set_cadastro_usuario, only: [:show, :edit, :update, :destroy]

  # GET /cadastro_usuarios
  # GET /cadastro_usuarios.json
  def index
    @cadastro_usuarios = CadastroUsuario.all
  end

  # GET /cadastro_usuarios/1
  # GET /cadastro_usuarios/1.json
  def show
  end

  # GET /cadastro_usuarios/new
  def new
    @cadastro_usuario = CadastroUsuario.new
  end

  # GET /cadastro_usuarios/1/edit
  def edit
  end

  # POST /cadastro_usuarios
  # POST /cadastro_usuarios.json
  def create
    @cadastro_usuario = CadastroUsuario.new(cadastro_usuario_params)

    respond_to do |format|
      if @cadastro_usuario.save
        format.html { redirect_to @cadastro_usuario, notice: 'Cadastro usuario was successfully created.' }
        format.json { render :show, status: :created, location: @cadastro_usuario }
      else
        format.html { render :new }
        format.json { render json: @cadastro_usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastro_usuarios/1
  # PATCH/PUT /cadastro_usuarios/1.json
  def update
    respond_to do |format|
      if @cadastro_usuario.update(cadastro_usuario_params)
        format.html { redirect_to @cadastro_usuario, notice: 'Cadastro usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @cadastro_usuario }
      else
        format.html { render :edit }
        format.json { render json: @cadastro_usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastro_usuarios/1
  # DELETE /cadastro_usuarios/1.json
  def destroy
    @cadastro_usuario.destroy
    respond_to do |format|
      format.html { redirect_to cadastro_usuarios_url, notice: 'Cadastro usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro_usuario
      @cadastro_usuario = CadastroUsuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cadastro_usuario_params
      params.require(:cadastro_usuario).permit(:nome, :senha, :funcao)
    end
end

app/controllers/cadastros_controller.rb
class CadastrosController < ApplicationController
  before_action :set_cadastro, only: [:show, :edit, :update, :destroy]

  # GET /cadastros
  # GET /cadastros.json
  def index
    @cadastros = Cadastro.all
  end

  # GET /cadastros/1
  # GET /cadastros/1.json
  def show
  end

  # GET /cadastros/new
  def new
    @cadastro = Cadastro.new
  end

  # GET /cadastros/1/edit
  def edit
  end

  # POST /cadastros
  # POST /cadastros.json
  def create
    @cadastro = Cadastro.new(cadastro_params)

    respond_to do |format|
      if @cadastro.save
        format.html { redirect_to @cadastro, notice: 'Cadastro was successfully created.' }
        format.json { render :show, status: :created, location: @cadastro }
      else
        format.html { render :new }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastros/1
  # PATCH/PUT /cadastros/1.json
  def update
    respond_to do |format|
      if @cadastro.update(cadastro_params)
        format.html { redirect_to @cadastro, notice: 'Cadastro was successfully updated.' }
        format.json { render :show, status: :ok, location: @cadastro }
      else
        format.html { render :edit }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastros/1
  # DELETE /cadastros/1.json
  def destroy
    @cadastro.destroy
    respond_to do |format|
      format.html { redirect_to cadastros_url, notice: 'Cadastro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro
      @cadastro = Cadastro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cadastro_params
      params.require(:cadastro).permit(:Nome, :Senha, :Funcao)
    end
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController

	def inicio
	end
	
	def exemplo1
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cadastro_usuarios_helper.rb
module CadastroUsuariosHelper
end

app/helpers/cadastros_helper.rb
module CadastrosHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/views/cadastros/_form.html.erb
<%= form_for(@cadastro) do |f| %>
  <% if @cadastro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cadastro.errors.count, "error") %> prohibited this cadastro from being saved:</h2>

      <ul>
      <% @cadastro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nome %><br>
    <%= f.text_field :Nome %>
  </div>
  <div class="field">
    <%= f.label :Senha %><br>
    <%= f.text_field :Senha %>
  </div>
  <div class="field">
    <%= f.label :Funcao %><br>
    <%= f.text_field :Funcao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cadastros/edit.html.erb
<h1>Editing Cadastro</h1>

<%= render 'form' %>

<%= link_to 'Show', @cadastro %> |
<%= link_to 'Back', cadastros_path %>

app/views/cadastros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cadastros</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Senha</th>
      <th>Funcao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cadastros.each do |cadastro| %>
      <tr>
        <td><%= cadastro.Nome %></td>
        <td><%= cadastro.Senha %></td>
        <td><%= cadastro.Funcao %></td>
        <td><%= link_to 'Show', cadastro %></td>
        <td><%= link_to 'Edit', edit_cadastro_path(cadastro) %></td>
        <td><%= link_to 'Destroy', cadastro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cadastro', new_cadastro_path %>

app/views/cadastros/new.html.erb
<h1>New Cadastro</h1>

<%= render 'form' %>

<%= link_to 'Back', cadastros_path %>

app/views/cadastros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cadastro.Nome %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @cadastro.Senha %>
</p>

<p>
  <strong>Funcao:</strong>
  <%= @cadastro.Funcao %>
</p>

<%= link_to 'Edit', edit_cadastro_path(@cadastro) %> |
<%= link_to 'Back', cadastros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeAcademy1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/paginas/exemplo1.html.erb
<html>
	<head>
		<title> USANDO CABEÇALHOS </title>
	</head>
	<body>
		<br><br>
		<font face="arial, verdana" color="#ff0000"><h2 align="center"> CAPÍTULO I - TÍTULO PRINCIPAL DO DOCUMENTO </h2></font>
		<br><br>
		<blockquote><font face="arial" color="#0000ff"><h3> 1.1 PRIMEIRO SUBTÍTULO </h3></font></blockquote>
		<br><br>
		<font face="arial" size="3" color="#000000">
			<p align="justify"> Este, é o 1º parágrafo deste subtítulo. </p>
			<p align="justify"> Este, é o 2º parágrafo deste subtítulo. </p>
			<p align="justify"> Continuação deste texto até a sua conclusão. </p>
		</font>
		<br><br>
		<blockquote><font face="arial" color="#0000ff"><h3> 1.2 SEGUNDO SUBTÍTULO </h3></font></blockquote>
		<br><br>
		<font face="arial" size="3" color="#000000">
			<p align="justify"> Este, é o 1º parágrafo deste subtítulo. </p>
			<p align="justify"> Este, é o 2º parágrafo deste subtítulo. </p>
			<p align="justify"> Continuação deste texto até a sua conclusão. </p>
		</font>
		<br><br>
		<blockquote><font face="arial" color="#0000ff"><h3> 1.3 TERCEIRO SUBTÍTULO </h3></font></blockquote>
		<br><br>
		<font face="arial" size="3" color="#000000">
			<p align="justify"> Este, é o 1º parágrafo deste subtítulo. </p>
			<p align="justify"> Este, é o 2º parágrafo deste subtítulo. </p>
			<p align="justify"> Continuação deste texto até a sua conclusão. </p>
		</font>
	</body>
</html>

app/views/paginas/inicio.html.erb
<head>
	<body>
		<br>

		<img src="http://imageshack.com/a/img903/908/piJ1VD.png" align="left" height="100" widith="100" >
		
		<!-- http://imageshack.com/a/img903/908/piJ1VD.png
		http://imageshack.com/a/img911/5268/bx0RjI.png -->
		

		<!-- <img scr=".\home\eduardo\Documentos/RubyE/discipule1.png" align="left" height="100" widith="100"> -->

		<blockquote><blockquote><blockquote>
			<font face="Slabo 27px" color="#0000B8"><h2> Discipule </h2></font></br>
		</blockquote></blockquote></blockquote>
		<!-- <h1 align="center">Cadastro de Conteúdos</h1></br></br> -->
		<br>
		<blockquote><font face="arial" color="#0000ff"><h2> Cadastro de Conteúdos Online </h2></font></blockquote>

		

		<br>
		<blockquote><font face="arial" color="#0000ff"><h3> 1.1 Cadastro de Usuário </h3></font></blockquote>
		
		<br>
		
		<font face="arial" size="3" color="#000000">
			<blockquote><blockquote><p align="justify"> Clique para cadastrar</p></blockquote></blockquote>
			<blockquote><blockquote><%= link_to("Cadastrar","cadastro") %></blockquote></blockquote>
		</font>


		<!-- <font face="arial" size="3" color="#000000">
			<p align="justify"> Este, é o 1º parágrafo deste subtítulo. </p>
			<p align="justify"> Este, é o 2º parágrafo deste subtítulo. </p>
			<p align="justify"> Continuação deste texto até a sua conclusão. </p>
		</font> -->

		<br>
		<blockquote><font face="arial" color="#0000ff"><h3> 1.2 Inserir </h3></font></blockquote>
		<br><br><br><br><br><br><br>

		<h5 align="center"><img src="http://imageshack.com/a/img911/5268/bx0RjI.png" align="center" height="40" widith="40" ></h5>
		<h5 align="center"><img src="http://www.lucianosimas.com.br/blog/wp-content/themes/wordpress-brown/images/sombra.gif" align = "center" height="40" widith="300"></h5>
		<!--
			<title>Title of the document</title></br></u>
			<p><u>This is a paragraph.</u></p></br>
			<h1><blockquote><blockquote><blockquote>This is a Heading</blockquote></h1></br>
			&nbsp; espaco
			<b>Negrito</b></br>
			<i> Itálico</i></br>
			<sub>Subscrito</sub></br>
			<u>Sublinhado</u></br> 
			<img src="w3schools.jpg" alt="W3Schools.com" width="104" height="142" 

		-->
	

	

		


	</body>
</head>

app/views/paginas/pagina2.html.erb
<head>
	<body>
		<br>

		<img src="http://imageshack.com/a/img903/908/piJ1VD.png" align="left" height="100" widith="100" >
		
	
		
		<br><br><br><br><br><br><br>
		<h5 align="center"><img src="http://imageshack.com/a/img911/5268/bx0RjI.png" align="center" height="40" widith="40" ></h5>
		<h5 align="center"><img src="http://www.lucianosimas.com.br/blog/wp-content/themes/wordpress-brown/images/sombra.gif" align = "center" height="40" widith="300"></h5>
	

	</body>
</head>